// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { config as loadEnv } from "dotenv";
import { defineConfig } from "prisma/config";

// `dotenv/config` only reads `.env`, but this project keeps its local
// connection string in `.env.local` (Next.js reads that automatically; the
// Prisma CLI does not). Without this, every `prisma db push` / `migrate` had to
// be prefixed with a manual `export DATABASE_URL=...`.
//
// Real environment variables always win — on Vercel DATABASE_URL is injected
// directly, so `override` stays false and nothing here can shadow it.
if (!process.env.DATABASE_URL) {
  loadEnv({ path: ".env.local", override: false });
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx ./prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
