// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { config as loadEnv } from "dotenv";
import { defineConfig } from "prisma/config";

// `dotenv/config` only reads `.env`, but this project keeps its local
// connection string in `.env.local` (Next.js reads that automatically; the
// Prisma CLI does not). Without this, every `prisma db push` / `migrate` had to
// be prefixed with a manual `export DATABASE_URL=...`.
//
// Real environment variables always win — on Vercel DATABASE_URL is injected
// directly, so `override` stays false and nothing here can shadow it.
if (!process.env.DATABASE_URL) {
  loadEnv({ path: ".env.local", override: false });
}

/**
 * Connection string for schema work (`db push`, `migrate`).
 *
 * Supabase's transaction pooler (port 6543, `pgbouncer=true`) multiplexes
 * statements across connections and cannot run DDL — pointing `db push` at it
 * makes the command hang until the build times out, which is exactly what
 * happened on the first deploy that enabled schema sync.
 *
 * Schema work therefore needs a session-mode connection. Prefer an explicit
 * DIRECT_URL when one is configured; otherwise derive it from DATABASE_URL by
 * moving to the session pooler on 5432 and dropping the pgbouncer flag, so this
 * works with no extra environment variables.
 *
 * This file configures the Prisma CLI only. The application runtime builds its
 * own client in src/lib/prisma.ts and keeps using the pooled DATABASE_URL,
 * which is the right connection for serverless request handling.
 */
function schemaUrl(): string | undefined {
  const explicit = process.env["DIRECT_URL"];
  if (explicit && explicit.trim()) return explicit;

  const url = process.env["DATABASE_URL"];
  if (!url) return undefined;

  return url
    .replace(":6543/", ":5432/")
    .replace(/([?&])pgbouncer=true&?/, "$1")
    .replace(/[?&]$/, "");
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx ./prisma/seed.ts",
  },
  datasource: {
    url: schemaUrl(),
  },
});
