// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { config as loadEnv } from "dotenv";
import { defineConfig } from "prisma/config";

// `dotenv/config` only reads `.env`, but this project keeps its local
// connection string in `.env.local` (Next.js reads that automatically; the
// Prisma CLI does not). Without this, every `prisma db push` / `migrate` had to
// be prefixed with a manual `export DATABASE_URL=...`.
//
// Real environment variables always win — on Vercel DATABASE_URL is injected
// directly, so `override` stays false and nothing here can shadow it.
if (!process.env.DATABASE_URL) {
  loadEnv({ path: ".env.local", override: false });
}

/**
 * Connection string for schema work (`db push`, `migrate`).
 *
 * Supabase's transaction pooler (port 6543, `pgbouncer=true`) multiplexes
 * statements across connections and cannot run DDL — pointing `db push` at it
 * makes the command hang until the build times out, which is exactly what
 * happened on the first deploy that enabled schema sync.
 *
 * Schema work therefore needs a session-mode connection. Prefer an explicit
 * DIRECT_URL when one is configured; otherwise derive it from DATABASE_URL by
 * moving to the session pooler on 5432 and dropping the pgbouncer flag, so this
 * works with no extra environment variables.
 *
 * This file configures the Prisma CLI only. The application runtime builds its
 * own client in src/lib/prisma.ts and keeps using the pooled connection, which
 * is the right one for serverless request handling.
 */
function schemaUrl(): string | undefined {
  // Must mirror the runtime's precedence in src/lib/prisma.ts exactly. Vercel's
  // Postgres integration injects POSTGRES_PRISMA_URL / POSTGRES_URL, and the
  // runtime prefers those over DATABASE_URL. When this file read DATABASE_URL
  // alone, `db push` reported "in sync" against one database while the app
  // queried another — the sync looked successful and production stayed broken.
  const db =
    process.env["POSTGRES_PRISMA_URL"] ||
    process.env["POSTGRES_URL"] ||
    process.env["DATABASE_URL"] ||
    process.env["POSTGRES_URL_NON_POOLING"];
  const direct = process.env["DIRECT_URL"]?.trim();

  // Supabase exposes three endpoints, and only one of them suits schema work
  // from a build container:
  //
  //   pooler:6543  transaction mode — what the app runtime uses. Multiplexes
  //                statements, so DDL hangs. Not usable here.
  //   db.<ref>...  direct connection. Runs DDL, but resolves to IPv6 only, and
  //                Vercel builds have no IPv6 route — this fails with P1001.
  //   pooler:5432  session mode. Runs DDL and is reachable over IPv4.
  //
  // So when DATABASE_URL is a pooler URL, derive the session-mode endpoint from
  // it: same host the runtime already reaches, just the port that allows DDL.
  // This deliberately takes precedence over DIRECT_URL, because a DIRECT_URL
  // pointing at db.<ref>.supabase.co is unreachable from here no matter what.
  if (db && db.includes(".pooler.supabase.com")) {
    return db
      .replace(":6543/", ":5432/")
      .replace(/([?&])pgbouncer=true&?/, "$1")
      .replace(/[?&]$/, "");
  }

  // Anywhere else (local Postgres, a non-Supabase host), an explicit DIRECT_URL
  // is the right answer when it is set.
  if (direct) return direct;
  return db;
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx ./prisma/seed.ts",
  },
  datasource: {
    url: schemaUrl(),
  },
});
