/**
 * /legal/content-policy — how Market Signals uses third-party news, and how a
 * publisher asks for removal. Linked from the footer of every /news page.
 * Takedown contact comes from CONTENT_TAKEDOWN_EMAIL (fallback RESEND_REPLY_TO).
 */
import React from 'react';

export const metadata = {
  title: 'Content policy — Market Signals | Property Tiger',
  description: 'How Property Tiger displays third-party news headlines, and how to request removal.',
};

const H2: React.CSSProperties = { fontSize: '1.05rem', fontWeight: 700, color: 'var(--color-text-hi)', margin: '28px 0 8px' };
const P: React.CSSProperties = { margin: '0 0 10px', lineHeight: 1.65, color: 'var(--color-text-mid)', fontSize: '0.92rem' };

export default function ContentPolicyPage() {
  const email = process.env.CONTENT_TAKEDOWN_EMAIL || process.env.RESEND_REPLY_TO || null;
  return (
    <div style={{ maxWidth: 760, margin: '0 auto', padding: '36px 20px 80px' }}>
      <h1 style={{ fontFamily: '"Plus Jakarta Sans", sans-serif', fontWeight: 800, fontSize: '1.8rem', color: 'var(--color-text-hi)', margin: 0 }}>
        Market Signals content policy
      </h1>
      <p style={{ ...P, marginTop: 8, color: 'var(--color-text-lo)' }}>How we show news from other publishers.</p>

      <h2 style={H2}>What we show</h2>
      <p style={P}>
        For each story we show the headline exactly as the publisher wrote it, the publisher&rsquo;s name, when it was published, and a link to the
        original article on the publisher&rsquo;s site. We find stories through the RSS feeds publishers make available and through Google News search
        feeds.
      </p>

      <h2 style={H2}>What we never do</h2>
      <p style={P}>
        We do not copy, store or display article text, and we do not display publisher photos or graphics; every image on the page is generated by us.
        We do not visit or scrape article pages. Links open the publisher&rsquo;s own page.
      </p>

      <h2 style={H2}>Our commentary</h2>
      <p style={P}>
        &ldquo;Our take&rdquo; and &ldquo;Why it matters&rdquo; notes are written by Property Tiger (with software assistance) in our own words, to explain
        what a story may mean for land and property buyers. They are clearly separated from the publisher&rsquo;s headline, they do not summarise or
        reproduce the article, and our systems reject any note that repeats the publisher&rsquo;s wording. They are general information, not legal,
        tax or investment advice. Always read the original article and verify with the relevant authority before acting.
      </p>

      <h2 style={H2}>Removal requests</h2>
      <p style={P}>
        If you are a publisher or rights holder and want a headline removed, or you believe something is inaccurate, contact us with the link to the
        story on our site. We remove headlines promptly once a request is verified; removed stories disappear from every feed.
      </p>
      <p style={P}>
        {email ? (
          <>
            Email: <a href={`mailto:${email}?subject=Market%20Signals%20takedown%20request`} style={{ color: 'var(--color-text-hi)', fontWeight: 600 }}>{email}</a>
          </>
        ) : (
          <>Please use the contact details on our website.</>
        )}
      </p>
    </div>
  );
}
